version: '2'

services:
  zimbra:
    image: zimbra_docker:latest
    #image: tonylixu/zimbra:version1
    environment:
      - VIRTUAL_HOST=zimbra-tony.lixu.com
      - PASSWORD=docker
    ports:
      - "25:25"
      - "80:80"
      - "465:465"
      - "587:587"
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
      - "443:443"
      - "8080:8080"
      - "8443:8443"
      - "7071:7071"
      - "9071:9071"
    hostname: zimbra-tony
    domainname: lixu.com
