version: "3"

services:
  zookeeper:
    # build: .
    image: tonylixu/ex-zookeeper
    networks:
      - zookeeper
    ports:
      - 2181
      - 2888
      - 3888
      - 8080
      - 8181
    volumes:
      - "./data/:/opt/zookeeper/local_configs/"
      - "./backup/:/opt/exhibitor/backup/"
networks:
  zookeeper:
