version: "3"

services:
  zookeeper:
    image: "micahhausler/docker-zk-exhibitor"
    networks:
      - zookeeper
    ports:
      - 2181:2181
      - 3888:3888
      - 8080:8080
      - 8181:8181
    volumes:
      - "./data/:/opt/zookeeper/local_configs/"
networks:
  zookeeper:
